name: Test
"on":
  push:
    branches:
      - main
      - dependabot/**
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 14.17
          - 16
        os:
          - ubuntu-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
          cache: npm
      - run: npm ci
      - run: "npm run test --ci"